"""empty message

Revision ID: 71916f21f4b2
Revises: 0f38ae6251a2
Create Date: 2023-04-02 20:55:15.856850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71916f21f4b2'
down_revision = '0f38ae6251a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
