"""empty message

Revision ID: 396782f45b70
Revises: 71916f21f4b2
Create Date: 2023-04-02 22:28:45.073583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396782f45b70'
down_revision = '71916f21f4b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
